---
title: "WV Tourism Shiny Map"
subtitle: "Fill out"
format: html
description: "Fill out"
date: "2024-05-24"
image: ../resources/images/
categories: ["R", "Project"]
number-sections: false
editor_options: 
  chunk_output_type: console
---

# Overview

This blog post will go over the project. Fill more of this later,

## Layout of Contents

Once I'm done with the blog post, write a map of the post so that people can skip to the part they are interested in the most because this will be a very big blog post I think.

# Import

## The Sitemap

All of the tourism related information for this app will come from the website itself, https://wvtourism.com. I think the website did a really good job of organized the articles and content, so I wanted to emulate that systematically using its sitemap. After a little bit of research, I found that most websites keep their sitemap at `https://example.com/sitemap.xml` or `https://example.com/robots.txt`. The `robots` pages directs you to <https://wvtourism.com/sitemap_index.xml> and manually going to <https://wvtourism.com/sitemap.xml> just redirects to the `sitemap_index.xml` page.

### The Sitemap Map

Looking at the links, you can see how the website has organized its information. After some investigation, I found only two of the index sitemaps relevant to this project, **Page** and **Company**.

| Applicable? | Sitemap                | Findings                                                             |
|-----------|------------------|--------------------------------------------|
| Yes         | Page                   | Contains all the directories in the website.                         |
| Yes         | Company                | Contains a page for every company mentioned through out the website. |
| No          | Tribe Events & Catalog | Contains past & future events.                                       |
| No          | Category & Tag         | Contains archives of posts with the relevant categories & tags.      |
| No          | Release & Posts        | Contains news releases and standalone articles.                      |

: Overview of index sitemaps.

After a lot of research, I decided that directories are a useful resource to explore the website, but will not be the map I was looking for. The website contains many circular links that are helpful when browsing as a user, but not so much when trying to build a scraping hierarchy.

## Geographical Data
