# Travel Regions ----
travel_regions = tribble(
  ~region,                         ~county,
  "Eastern Panhandle",             "Berkeley County",
  "Eastern Panhandle",             "Jefferson County",
  "Eastern Panhandle",             "Morgan County",
  "Hatfield-McCoy Mountains",      "Boone County",
  "Hatfield-McCoy Mountains",      "Lincoln County",
  "Hatfield-McCoy Mountains",      "Logan County",
  "Hatfield-McCoy Mountains",      "McDowell County",
  "Hatfield-McCoy Mountains",      "Mercer County",
  "Hatfield-McCoy Mountains",      "Mingo County",
  "Hatfield-McCoy Mountains",      "Wayne County",
  "Hatfield-McCoy Mountains",      "Wyoming County",
  "Metro Valley",                  "Cabell County",
  "Metro Valley",                  "Kanawha County",
  "Metro Valley",                  "Mason County",
  "Metro Valley",                  "Putnam County",
  "Mid-Ohio Valley",               "Calhoun County",
  "Mid-Ohio Valley",               "Jackson County",
  "Mid-Ohio Valley",               "Pleasants County",
  "Mid-Ohio Valley",               "Ritchie County",
  "Mid-Ohio Valley",               "Roane County",
  "Mid-Ohio Valley",               "Wirt County",
  "Mid-Ohio Valley",               "Wood County",
  "Mountain Lakes",                "Braxton County",
  "Mountain Lakes",                "Clay County",
  "Mountain Lakes",                "Gilmer County",
  "Mountain Lakes",                "Lewis County",
  "Mountain Lakes",                "Nicholas County",
  "Mountain Lakes",                "Upshur County",
  "Mountain Lakes",                "Webster County",
  "Mountaineer Country",           "Barbour County",
  "Mountaineer Country",           "Doddridge County",
  "Mountaineer Country",           "Harrison County",
  "Mountaineer Country",           "Marion County",
  "Mountaineer Country",           "Monongalia County",
  "Mountaineer Country",           "Preston County",
  "Mountaineer Country",           "Taylor County",
  "New River - Greenbrier Valley", "Fayette County",
  "New River - Greenbrier Valley", "Greenbrier County",
  "New River - Greenbrier Valley", "Monroe County",
  "New River - Greenbrier Valley", "Raleigh County",
  "New River - Greenbrier Valley", "Summers County",
  "Northern Panhandle",            "Brooke County",
  "Northern Panhandle",            "Hancock County",
  "Northern Panhandle",            "Marshall County",
  "Northern Panhandle",            "Ohio County",
  "Northern Panhandle",            "Tyler County",
  "Northern Panhandle",            "Wetzel County",
  "Potomac Highlands",             "Grant County",
  "Potomac Highlands",             "Hampshire County",
  "Potomac Highlands",             "Hardy County",
  "Potomac Highlands",             "Mineral County",
  "Potomac Highlands",             "Pendleton County",
  "Potomac Highlands",             "Pocahontas County",
  "Potomac Highlands",             "Randolph County",
  "Potomac Highlands",             "Tucker County"
)

# Zip Codes ----
zips = read_csv("Data/us_zips.csv", col_types = "ccccccn") |>
  select(-type)
